source 'https://rubygems.org'
ruby '2.0.0'

gem 'sinatra'
gem 'slim'
gem 'sass'
gem 'coffee-script'
gem 'sinatra-contrib'
gem 'dotenv'
gem 'force'
gem 'hashie', '~> 1.2.0'
gem 'thin'
gem 'foreman'
gem 'metaforce', git: 'https://github.com/ejholmes/metaforce.git'
